### ISSUE TITLE
"Don't Use Emote Bypass if Emote is Unlocked" doesn't skip Twitch-unlocked emotes

### ISSUE THREAD

**Issue by Milous98** [riolubruh/YABDP4Nitro#102]
Hi, good job on this plugin, I've been looking for something like this for quite a while ! But it seems like the "Bypass Emote if Emote is Unlocked" is not working correctly. I already read all other issue posts about it and it seems to be coming back every now and then. 

![image](https://github.com/riolubruh/YABDP4Nitro/assets/26144344/ddc23feb-6bed-4fd4-811f-8a227bbf9ec6)

To explain the issue, this is what happens when I'm in my own server, using my server emotes (the 2 bottom monkaW) and an emote from an other server (the middle one) where I'm sub at (so I have all Twitch emotes from this server) If all 4 options are checked like in the screen, emotes from my server will uplad correctly as emotes, but those from the server I'm sub at are uploaded as images instead of emotes

![image](https://github.com/riolubruh/YABDP4Nitro/assets/26144344/93db3425-0754-41da-800e-3f2021f14641)

But if I uncheck "Nitro Emote Bypass", they are uploaded as emotes as they should (the top one).

I tried using original 0PluginLibrary.plugin.js as well as the one you provide and it's the same. What is odd is when I'm in an other server where I should be able to use emotes, some are also uploaded as images instead of emotes. So for now I just disabled the "Emote Bypass" as it got me TO in some discord where I can't post links (eventhough I have legit access to the emotes I'm using)

**Comment by riolubruh** [comment]
As you mentioned, this issue has been known about, and technically the option _is_ working correctly, but the problem is that it currently only checks if the emoji is from the server that you are currently in. The plugin used to use the "`isEmojiFilteredOrLocked`" function, however that method of checking the emoji's availability [stopped working quite a while ago](https://github.com/riolubruh/YABDP4Nitro/commit/4cf2fcdf6fa07b884b15de285d9a4bceb6890fd0#diff-fd1f38a98b2f483a8c3c554e744adfdf142e2902691239727545356e441d84b0L222), since the function would always return false since the function believed that the user has Nitro and therefore all emojis should be unlocked according to that function. The problem with trying to change how that function works is that I believe that the Emoji Menu uses that function to determine which emojis should appear locked/unlocked(?). I'm not sure if there is a function to check if a specific emoji is twitch-unlocked or not, so yeah, it's not as simple as it probably should be.

**Comment by Milous98** [comment]
![image](https://github.com/riolubruh/YABDP4Nitro/assets/26144344/6874f337-51aa-4504-9ac1-4f4e8120d54d)

Oops sorry I missclicked on that

**Comment by riolubruh** [comment]
> if I'm posting on a Discord an emote from this Discord, the emote is posted as an image, BUT if I write something before and add the same emote in the sentence, it is posted as an emote

If that part is true, that's unintentional and therefore is actually a bug. If an emote is from the server you are in, it is supposed to always post as an emote, as in no emoji bypass should occur. I will look over the code for the emoji bypasses to see if there is a mistake with that.

**Comment by Athenya** [comment]
Would like to add that I'm also having a similiar issue where using an emoji that I have access to through Twitch subscriptions results in it being posted as an image.

**Comment by Athenya** [comment]
Would it be possible to add a feature where adding something like \ before the emoji would force it to not use the emote bypass?

**Comment by riolubruh** [comment]
> Would it be possible to add a feature where adding something like \ before the emoji would force it to not use the emote bypass as a sorta workaround to this issue?

Yes!

**Comment by riolubruh** [comment]
> Would it be possible to add a feature where adding something like \ before the emoji would force it to not use the emote bypass as a sorta workaround to this issue?

Added in 4.5.5! Thanks for the suggestion!
