### ISSUE TITLE
Account Disabled - Violation of TOS

### ISSUE THREAD

**Issue by TeeXX** [riolubruh/YABDP4Nitro#107]
Hey, I'm not here to complain, just to report that my account got suspended after using this plugin for a few days.

I've created a new account just for streaming Full HD 30fps on my own server with a few friends.

It's still possible that there was another reason, but It seems improbable, I've been using this account ONLY for this feature (fear of getting ban on my main)

All I did was to join my server, join voice call, mute and start a stream, after few hours I left.

Thanks for creating this plugin and stay safe guys, cheers!

![image](https://github.com/riolubruh/YABDP4Nitro/assets/104693278/34087746-b702-4fee-8919-8d10e4739958)

**Comment by riolubruh** [comment]
Thanks for letting me know.
It's also possible that Discord flagged you as a **spam account** due to it being a new account without a lot of activity other than joining voice calls and streaming, which may have been flagged as "self-botting" (even though it wasn't).
Other than that possibility, it's also just as valid to assume that this is due to the use of this plugin / BetterDiscord. The email is just vague enough that it could be either, but due to the part where Discord T&S says "Discord has disabled your account for **spam and/or platform abuse**," I'm leaning towards it being flagged as spam (though I am a bit biased lol).

**Comment by TeeXX** [comment]
I just got an email an hour ago after issuing a ticket, and the ban was lifted.
They say that I was caught in a spam filter, so you were right.

I wanted to post this asap as it might have been a ban wave for this plugin and/or similar to.

Anyway, thanks for responding so soon! Cheers
