### ISSUE TITLE
I can't put emojis in bio 

### ISSUE THREAD

**Issue by xARMR** [riolubruh/YABDP4Nitro#109]

**Comment by riolubruh** [comment]
If by "bio" you mean the About Me section of the profile, yeah I think you can only put system (default) emoji in there (for obvious reasons). If you want a bit more customizability, you can should, however, be able to use Unicode characters iirc, which should allow you a decent amount of customizability.

If you're thinking about a custom status, then the same kind of thing applies; i.e. only default emoji are possible because the server will disallow you from using emojis that aren't actually unlocked.
