### ISSUE TITLE
no nitro upsell

### ISSUE THREAD

**Issue by speedlorenzo12** [riolubruh/YABDP4Nitro#118]
(a plugin of replugged) removes all nitro upsells like profile ones (removes buttons of nitro ecc) can you do a setting like that on your plugin?
unfortunately I can not explain it too well it is better if you go and see
(I know a new nitro feature not released yet and discordbypasses is now discontinued )

**Comment by riolubruh** [comment]
Currently, the "Copy 3y3" button will only appear if the nitro upsell in the profile customizer is present, since the function used to check if that page is currently open is `getAllTryItOut`. I can remove the upsell there by patching the `canUsePremiumProfileCustomization` function to return `true`, however, since there is currently no code to add the "Copy 3y3" button on the screen when the "Try It Out" nitro upsell is not present, you won't be able to change your accent color if the nitro upsell there is removed (for now at least). 

However, you can remove a couple upsells (such as the screen share one) by adding this to the bottom of your Custom CSS:
```css
[class*="upsell"] {
  visibility: hidden;
  height: 0;
  width: 0;
  margin: 0;
}
```

**Comment by speedlorenzo12** [comment]
now i really like this bypasser but in the future there will be profile effects feature (a lot in alpha) but i'm sorry about discontinuation of discordbypasser plugin but thanks to that discontinuation i discovered your plugin :) and given a lot of suggestions

**Comment by riolubruh** [comment]
The Discord update's changes unfortunately broke the code that removed the upsell in the Profile Customization menu.
Unfortunately, this necessitated (temporarily) removing the feature for 4.7.0. Sorry about that lol

**Comment by speedlorenzo12** [comment]
Can you fix this?

**Comment by riolubruh** [comment]
> Can you fix this?

I've tried looking for a way to remove the profile customization upsell each time I was working on a new update, but I kept on coming up empty-handed. As far as I know, it seems that the only way to remove that upsell that I know of is to set the current user's premiumType to 2 (which is something I actively try to avoid having to do).
If you don't care about the potential negative side effects of changing the premiumType to 2, you are always free to modify the plugin's code yourself in order to do so, however, for the time being, it will be left out of the plugin until a more elegant solution is found.
