### ISSUE TITLE
Streaming at higher quality does not work after update

### ISSUE THREAD

**Issue by Shadow-MrShadow** [riolubruh/YABDP4Nitro#132]
Hello, i have this problem as mentioned in title, i can not stream in higher quality after plugin upgrade. It is crucial function for me, i do stream a lot on discord but i do not want to pay for Nitro. Can this be fixed somehow?

**Comment by riolubruh** [comment]
I've had a couple reports of this issue, and it's really weird because it only seems to affect some people for some reason.
Like, it works fine for me, for example, and K3NOXOFFICIAL also said it worked for him...
Either way, for now the workaround is to enable "Change PremiumType" in settings under Miscellaneous

**Comment by Shadow-MrShadow** [comment]
thanks, it helped!
