### ISSUE TITLE
add custom icons

### ISSUE THREAD

**Issue by ELJoOker2004** [riolubruh/YABDP4Nitro#142]
add custom icons if possibles

**Comment by ELJoOker2004** [comment]
![image](https://github.com/riolubruh/YABDP4Nitro/assets/62572632/52ac1d21-6d0e-4e6c-a38b-0d4e84395656)
will this change it here u sure?

**Comment by riolubruh** [comment]
No, it will only change the application's icon and not the one in the top left corner

**Comment by ELJoOker2004** [comment]
np , that's why i was asking for this feature , could be nice

**Comment by riolubruh** [comment]
well this was surprisingly easy...
![asd](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/04e0e4cc-f683-4097-8ff4-f3ce4f3d125e)
it works in a very similar way as the nitro gradient themes do, except a little simpler since they don't sync the icon.
I had to enable the experiment for the in app icons manually so I guess not every user will be able to appreciate it yet

**Comment by ELJoOker2004** [comment]
very nice , thanks for you efforts and you fast reply , good luck <3

**Comment by riolubruh** [comment]
OK I can't figure out how to get around the fact that it requires premiumType to be set so I'm just gonna make it so that it forces Change Premium Type to be enabled.

**Comment by riolubruh** [comment]
Added in 4.8.6 (7549452).
Thank you for your suggestion.
