### ISSUE TITLE
Question about function "Fake Profile Themes"

### ISSUE THREAD

**Issue by KozhurYT** [riolubruh/YABDP4Nitro#145]
Hello, @riolubruh!
I have a some question about this function. Can it work if I put 3y3 to status, if it work say me how/.

**Comment by riolubruh** [comment]
No. For Fake Profile Themes you have to put the 3y3 in your **bio** (the "About Me" section of your profile). There's no reason to put the 3y3 for Fake Profile Themes in your status since you can only see your fake profile theme once you have opened your profile at least once, meaning that there would be no benefit to having the ability to put the 3y3 of fake profile themes in your status (since the benefit of putting 3y3 in your status is that other users don't have to open your profile to download your bio)
