### ISSUE TITLE
Audio/Video desync with higher bitrates

### ISSUE THREAD

**Issue by 3941** [riolubruh/YABDP4Nitro#155]
Well, I can't say if it's the newer plugin or the newer Discord version itself that causes this, but it wasn't an issue before either update happened. Granted, I couldn't test it until the plugin updated, naturally.

When I choose higher bitrates, the video will start lagging behind the audio and it gets progressively worse.
When I only use the Nitro streaming unlock and use Discord's presets, this doesn't happen.

I've tried a few different bitrates and FPS to mitigate this, with no success.
The bitrate does reach the viewer, though. That doesn't seem to be the issue. It also doesn't seem lower than before, which is what you might expect when the video is, apparently, running slower.

I'm testing this with 2 Discord accounts and Discord standalone + one in the browser.

**Comment by 3941** [comment]
I just streamed for hours at nitro quality, but standard settings, and it was perfect all the way through....
Once I choose custom bitrates, things go bad.

**Comment by riolubruh** [comment]
This could just be due to having too high of a bitrate, but considering it didn't happen before, there's a possibility that Discord maybe changed something server-side that's causing issues at bitrates that are higher than intended...? It's also possible that they may have changed something in the client surrounding screen share.

**Comment by 3941** [comment]
How much influence can you even get over the codec? And how much do you use?
Do you just change the bitrates, or is it a whole command that's being sent, setting other encoding flags, like CBR, VBR, etc....
I have no idea how it works internally.

**Comment by riolubruh** [comment]
- [ ] There are a _shocking_ amount of streaming parameters, some of which even I do not understand completely. For bitrates specifically, the plugin modifies an otherwise unused list of parameters under bitrateOverride which changes the minimum, target, and maximum encoding and decoding bitrate to the specified number (in bits per second; the plugin simply multiplies the inputted value to convert the kbps inputted into bps). There are also multiple different video codecs that can be used, if I remember correctly there's H.264, AV1, VP9, and VP8(?). **Discord screen share uses adaptive bitrate**, but if you set the minimum, target, and maximum bitrate to the same value, it would theoretically provide a similar experience to constant bitrate, but I would advise _against_ doing that. Also within the stream parameters are all of the encoding ladders (which I'm not gonna lie, I had to look up what that is). The plugin currently only changes the framerate values of the encoding ladders, since I didn't really know what those were when I was making the bypass, and I'm not entirely sure if modifying the encoding ladders actually has an effect on the stream (though it would probably be worth remedying that and changing the resolutions accordingly, at least for peace of mind), as even without changing the ladder resolutions the stream does typically look a lot better with a modified resolution than without...

**Comment by 3941** [comment]
So if no bitrate is set natively, maybe it'd be better to adjust the quality?
Is there a CRF or RF, or maybe quality, variable?

**Comment by riolubruh** [comment]
Discord *does* have default bitrates, but frankly, they're not very good.
**Discord's default bitrates are:**

Bitrate Floor: 150kbps

When streaming desktop:
-Min Bitrate: 500kbps
-Target Bitrate: 600kbps
-Max Bitrate: 4000kbps
When streaming an application:
-Min Bitrate: 150kbps
-Max Bitrate: 2500kbps

Different sources recommend different bitrates for different resolutions, but all of Discord's default bitrates are seemingly too small for a smooth and consistent 1080p@60fps. Most people recommend a bare minimum of around 5000kbps for 1080p60 with the max being in the 9000-10000 range (and the target value somewhere in the middle between 5000 and 9000, maybe 7000 or 7500).

I made a version that changes all of the encoding ladders to be proper and is generally more thorough with applying bitrate and quality options that you can test, although I don't know if it will make any difference by itself.
Modified version: [YABDP4Nitro.plugin.zip](https://github.com/riolubruh/YABDP4Nitro/files/13222247/YABDP4Nitro.plugin.zip)

**Comment by 3941** [comment]
Just gave it a try.
While the streaming side of Discord doesn't object at all and appears to be streaming, the client side doesn't even see that there's a stream going and can't watch it.

**Comment by 3941** [comment]
Wait, maybe that's not related to your plugin...
I can't say I've ever seen this happen before, but the same thing now happens with the public version of your plugin, as well as without the plugin at all... Maybe Discord has streaming issues currently, I dunno.

**Comment by 3941** [comment]
Well, this is really odd, but somehow I can't watch it in my own browser anymore. I just did it like two days ago and now nada.
I've tried two different other devices, a tablet and a phone, and those seem to work fine.
The video is in sync though I don't trust the fluidity without seeing it on a big screen and a device I know can play video fluidly.

Quality looks good, better than without the manual bitrate, on the small screens anyway, though the bitrate seems low overall, just going by the amount of data I see I'm uploading. It's still a bit higher than default and clearly looks better, particularly on sudden scene transitions.
I've set quite a big range of possible rates, though. I'll have to try a higher minimum rate.

**Comment by 3941** [comment]
Increasing the minimum rate I'm getting the same desync issue as before... Still, I think it looks better overall than just Nitro with the settings I have now. But I'm also just testing it on a tiny screen...
I guess they've just changed stuff with that update and we aren't getting as much freedom as before.
Can't blame them, it's their service after all. I'm sure at some point they'll drop the hammer on the wild west, that is streaming on Discord, anyway.

**Comment by riolubruh** [comment]
It could also be caused by a few other factors, which leads me to some questions I have about your PC and Internet:
What are your PC specs?
How fast is your Internet (upload speed especially)?
Is your Internet wired or wireless?
Is Hardware Acceleration enabled in Discord settings?

**Comment by 3941** [comment]
ryzen 5950x
radeon 6700xt
about 37mbits upload speed, wired
hardware acceleration ofc enabled

I had no issues streaming at 10 to 12 mbits before. (target 10, max 12, min 8) 
Didn't seem to make any sense going higher and made for a really nice picture.
The only thing that changed is that big Discord update. And possibly something on their servers, I dunno, though apart from the desync issue, the higher bitrate is still going through their servers seemingly unchanged.

**Comment by 3941** [comment]
It seems like minimum bitrate is king...
Even if I set target and max significantly higher, it sticks to streaming at minimum bitrate.

**Comment by 3941** [comment]
Okay that's funny... I thought why don't I try software encoding, and the desync is gone.
The picture is a lot worse, though. Even with massively increasing the bitrate, it's still worse, plus apparently it can't cope when lots of stuff happens and starts to stutter in motion heavy scenes. Although I have a fantastic CPU for encoding, it's barely being used.

**Comment by 3941** [comment]
Well, best I can do is 4500kbit min bitrate (others don't matter) with hardware encoding, at 720p 60fps... 60 because it just seems smoother. Probably because it's potentially missing less frames from whatever the source material is.
At least it's slightly higher quality than Discord's default.

**Comment by riolubruh** [comment]
Discord streaming is so fucking weird lol

**Comment by 3941** [comment]
Happy to report it seems to have fixed itself. On my end at least.
Guess it must have been one of those other Discord updates they pushed.

**Comment by 3941** [comment]
Streamed for people at 12mbits last night and they didn't complain :)

**Comment by 3941** [comment]
Well, I know you likely can't do anything about it, but looks like they broke it again...
Just wanted to note that here, if anyone else is looking.
