### ISSUE TITLE
userbg and userpfp integration

### ISSUE THREAD

**Issue by speedlorenzo12** [riolubruh/YABDP4Nitro#159]
integrate userbg and userpfp (other databases) as an alternative to fake profile banners and pfp

**Comment by riolubruh** [comment]
There's two ways I could implement this:

Sane person way:
Just import the userbg and userpfp css c:

**Deranged lunatic method:**
**manually parse and import the entire userbg and userpfp json data with js**

**Comment by speedlorenzo12** [comment]
I would go for the sane person, but one is supported very little, the other plugin 1 does not exist for bd

**Comment by riolubruh** [comment]
Progress update: ok so just importing the userpfp css worked perfectly *for userpfp*, but unfortunately I couldn't get the same to work for userbg, so for userbg I ended up having to script the plugin to download and process the ~8mb userbg JSON file (...so I ended up having to do both the sane method _and_ the deranged method).
In an effort to make performance not completely fucking die, I made it so it only downloads the userbg json **on plugin start**.
I also realized that Discord made it so that banners only appear on users that have Nitro (and therefore render with the gradient profile theme), so I made it so that any user that has a banner (either a yabdp4nitro fakebanner or a userbg banner) will appear with the gradient profile theme (since otherwise the banner does not display)
ex: ![](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/7da01438-4d6e-4114-8794-a8d7183a809f)
as you can see, the user isn't using yabdp4nitro, _and_ doesnt have nitro, but because of userbg, they still have a banner

**Comment by riolubruh** [comment]
Added in 5.0.3. Thanks for your suggestion @speedlorenzo12!
