### ISSUE TITLE
Imgur CORB issue

### ISSUE THREAD

**Issue by J-Stuff** [riolubruh/YABDP4Nitro#162]
It appears Imgur has enabled CORB on it's site, or a bypass to it that used to work in the plugin has broken.
This is affecting both the PFP & Banner features.

![image](https://github.com/riolubruh/YABDP4Nitro/assets/68690676/b75b32b5-e045-4ef5-b202-af1ad8efe083)
![image](https://github.com/riolubruh/YABDP4Nitro/assets/68690676/d43dece7-615c-4831-9306-5e7c8900569c)

**Comment by riolubruh** [comment]
The URL in the log is incorrect. Try right clicking on the image on the Imgur page and clicking "copy image address" and using that URL instead

**Comment by J-Stuff** [comment]
That works now, Thanks for the help. Though it might help if the plugin made it more clear in the Profile menu.

**Comment by riolubruh** [comment]
I finally found a way to automatically grab the direct link from imgur Album urls (imgur urls that contain the /a/)
![](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/1705d4e5-7543-4c1b-b11d-51e341a243a9)
using this, we can finally get rid of errors caused by album URLs, and it should be included in the next update!
