### ISSUE TITLE
[BUG] Opening the Account Panel breaks experiments

### ISSUE THREAD

**Issue by speedlorenzo12** [riolubruh/YABDP4Nitro#164]
your profile or another is the same

**Comment by riolubruh** [comment]
?????

**Comment by riolubruh** [comment]
I... don't see anything wrong??

**Comment by speedlorenzo12** [comment]
The experiments gone when i returned in the settings

**Comment by riolubruh** [comment]
Ah, I see it now lol. Yeah, I'm not exactly sure why, but for some unfathomable reason, opening that specific menu breaks both App Icons and apparently also Experiments.

**Comment by riolubruh** [comment]
Still not exactly sure what exactly causes it, it's something that happens during the rendering of the account panel...
..._but_ either way I _did_ find a way to workaround the issue.
It seems like opening the account panel, like, kind of like re-fetches the current user or something for some reason...?
So the workaround is to correct the premiumType and flag values (for app icons and experiments respectively) after the account panel renders.
The app icon will flash blue, but the experiments won't have anything weird like that happen since ig that function doesn't check the user flags as often? idfk honestly lol
