### ISSUE TITLE
is this possbile to do in chrome browser

### ISSUE THREAD

**Issue by Turkisec** [riolubruh/YABDP4Nitro#17]
is this posbbile to do in chrome browser becase they onnly allow 720p 30fps even with nitro

**Comment by riolubruh** [comment]
Good question...
currently there is no way to run BD plugins directly on Chrome as far as I know.
Fair warning: There is a "BetterDiscord extension" however **DO NOT USE IT!** It will steal your account!
As for a possible bookmarklet/userscript/extension version of this plugin, I would have to do some research.
I have never developed a chrome extension before, so don't count on that any time soon, however maybe a minified version of this plugin could be crammed into a userscript or a bookmarklet(?). Tbh that would be pretty lit if it's possible, but I'll have to look into it deeper since without BetterDiscord, it could be quite difficult to locate and modify a Discord module. If we go off the assumption that it's possible, it would probably be very difficult to make custom resolutions. Still, unlocking the 1080p/Source/60FPS options is actually relatively easy as long as the "permissions module" (Ok it's not actually called that but I nicknamed it that for being the place where the client stores info about what the user is allowed to do, for example canUsePremiumResolutions and canUsePremiumFPS) can be found. 
Alternatively, you could also try to find the module that stores what premiumType you need to use each resolution/fps option. Overall, this is a good question but not one that I can answer at this time. The fact is that without BetterDiscord's plugin features you would have to get creative and really stretch what JavaScript can do; however, it's certainly not impossible.
Anyways, I hope this helps. The answer at the current moment is: **TL;DR:** "It could feasibly be done but has not yet to my knowledge."

**Comment by riolubruh** [comment]
You can try (https://github.com/Strencher/BdBrowser) or its updated fork (https://github.com/tsukasa/BdBrowser) for this purpose. Use at your own risk.

**Comment by Turkisec** [comment]
i tested it it seems is not updating maybe the limt is 720?? on chrome
