### ISSUE TITLE
[BUG REPORT] Doesn't send Spotify listen along invite

### ISSUE THREAD

**Issue by ThEGuYwItHSuP** [riolubruh/YABDP4Nitro#193]
If you try to invite someone using the "Invite @username to Listen to Spotify" whilst the plugin is activated it wont send the invite.

**Comment by riolubruh** [comment]
You just mentioned the GitHub user with the username "user".
Also I'll look into it soon.

**Comment by ThEGuYwItHSuP** [comment]
i meant as in the promt. it can be any username. "Invite @(enter username here) to Listen To Spotify"

**Comment by riolubruh** [comment]
I know, but you can also mention GitHub users by name like that, and I'm pretty sure it notifies them when someone @'s them

**Comment by ThEGuYwItHSuP** [comment]
Wanted to ask how is the search going?

**Comment by riolubruh** [comment]
The problem is with the following code:
```js
if((msg[1].content !== undefined && msg[1].content != "") && runs == 0)
```
Basically, it sees that the message content is empty, and cancels the message.
Spotify invites and other `activityAction`s are an exception where a message with no content is allowed on the API, so I didn't add a case for it.
The fix is simply to add a special case where if an `activityAction` is included in the message parameters, the empty content of the message is ignored.
