### ISSUE TITLE
Is this bannable?

### ISSUE THREAD

**Issue by balls-gaming** [riolubruh/YABDP4Nitro#22]
Will my account get deleted if I use this plugin? I know the emojis aint an issue since they're just links but the screensharing and the fact that it seems to work has me worried.

**Comment by riolubruh** [comment]
BetterDiscord itself is technically against TOS and this plugin probably is too.
As far as I know, nobody has really been banned for using BD or this plugin since Discord has not implemented any detection for modified clients. Use it at your own risk, however **as the maintainer of this plugin I have been using it for multiple years with no issues.**
