### ISSUE TITLE
premiumType discrepancy

### ISSUE THREAD

**Issue by minhla** [riolubruh/YABDP4Nitro#23]
I'd love to use full HD screen share, but I don't really want to use the free emotes feature, so if there is a toggle in the settings for each feature it would be nice.

**Comment by Pickymarker** [comment]
just disable emoji bypass

**Comment by riolubruh** [comment]
keeping this issue open purely because you currently do not have the option to _not_ change your premiumType

**Comment by KDunny** [comment]
> just disable emoji bypass

Disabling emoji bypass still shows emotes as unlocked in the emoji menu for me.

**Comment by riolubruh** [comment]
> Disabling emoji bypass still shows emotes as unlocked in the emoji menu for me.
Indeed, this is known about. It's as a result of the plugin changing the premiumType.

The Sticker menu would also be unlocked if the premiumType was set to 2 (instead of 1) 
(although, a bypass function would still be needed).

If a function for handling stickers is added, it will most likely be necessary to set premiumType to 2, at least while it is enabled.
This creates a problem in the case where the Emoji bypass is disabled while a Sticker bypass is _enabled,_ the fix being the premiumType (or some other variable[s]) would have to be modified _while_ the Emoji and/or Sticker menus are being opened/rendered.
