### ISSUE TITLE
Fake Profile Pictures Lag

### ISSUE THREAD

**Issue by Doomelf** [riolubruh/YABDP4Nitro#233]
When I toggle fake profile pictures am getting lag when mousing over discord UI, and freezes when changing servers or channels. Persists after disabling all other plugins. Haven't even used the setting before. Disabling it fixes the lag.

**Comment by riolubruh** [comment]
idk whether to consider this a bug or what but I will try to get around to it eventually

**Comment by riolubruh** [comment]
I made a small optimization in 5.5.1, but it's likely not what's causing your issue. If there's anything in console that would be good.
I should also mention that sometimes large themes can sometimes cause lag issues, usually as a result of "forced reflows" where all of the CSS in the page has to be recalculated essentially.
If you know how, you can also use the Performance tab in DevTools to help figure out what specifically is causing the lag, since it doesn't occur on my machine.

**Comment by riolubruh** [comment]
?
