### ISSUE TITLE
Error loading FFmpeg.wasm -- unable to verify the first certificate

### ISSUE THREAD

**Issue by Doomelf** [riolubruh/YABDP4Nitro#234]
![image](https://github.com/user-attachments/assets/75f28d2e-18cd-465f-ada6-7b768e814ea7)

**Comment by riolubruh** [comment]
Dear god not TLS errors. This is not really something I can control as a plugin developer, as the browser itself should handle network stuff like this. This error also can happen with the the BD installer itself, and their advice is basically:
- reinstall discord/betterdiscord
- try restarting your computer once or twice and see if it works
- disable any proxy or vpn and see if it works
- enable a US vpn and see if it works

Good luck. TLS is a nightmare sometimes.

**Comment by Doomelf** [comment]
Tried using previous versions and the error appears with versions 5.5.1 and above, but not 5.5.0 and under. Not gettting it from other plugins either.

**Comment by riolubruh** [comment]
That's because the clips bypass feature which uses FFmpeg.wasm was only added in 5.5.1.
If you aren't planning on using it, you can turn it off under Clips in the plugin settings.
You could try changing the URLs of the FFmpeg fetches to be `http://` instead of `https://` to see if that helps, ex:
![Code_zqOczeiMV7](https://github.com/user-attachments/assets/0def462b-4466-4bd8-9e9b-7bcf6eb8cbaf)
But, it will probably automatically try to upgrade the connection to HTTPS and still fail...

I'll see if there's a way to truly disable HTTPS for this fetch and get back to you.

**Comment by riolubruh** [comment]
You cannot disable HTTPS for unpkg.
Seems the only way around this problem is to load FFmpeg.wasm from another server or load it from the hard drive.
Sorry.

**Comment by riolubruh** [comment]
Might consider adding a way to load the files from disk, since you're not the only one with this problem.

**Comment by riolubruh** [comment]
Did some experimenting with help from another user with the same issue. Seems the browser fetch doesn't have this issue. Should be fixed in 5.5.7 (0718271). If it isn't, please reply to this issue.
