### ISSUE TITLE
Can't get framerate above 40 in 1080.

### ISSUE THREAD

**Issue by refriedfood** [riolubruh/YABDP4Nitro#62]
Though, I can get 60+ in 1280x720. It's a strange problem I'm having where the fps seems to vary just standing still. I usually record/stream using obs at 60 constant, so it isn't a hardware issue. I'm wondering if it's just a lack of Discord optimization or if anyone else has noticed this issue, and what can be done--this is for streams of applications/games, not just a stream desktop.

**Comment by riolubruh** [comment]
Discord streaming is not as good as OBS, period. However, with a fast and stable connection you should be able to get it to 60FPS. I recommend enabling custom bitrate options and tweaking with it, as due to how Discord streaming works it may decide to lower the framerate in order to prioritize the 1080 or vice versa. For 1080p 60FPS I would recommend a minimum bitrate of 4500, a target bitrate of your choosing, (I personally use around 6000-6500) and a maximum bitrate around 9000 kbps or higher. Although Discord will never perfectly match the output of OBS, it can usually (at least) be improved in this way.

**Comment by refriedfood** [comment]
Thanks for the suggestions, I will try them out.

**Comment by riolubruh** [comment]
Closing assuming it's been resolved

**Comment by refriedfood** [comment]
That's fine. Sorry for the late reply. I couldn't get this resolved, however, streaming at 720 with it gave me 60fps. I have a 1Gbps connection and used your settings and still didn't receive the desired/usable results. But if it's a discord limitation, there isn't much I can do. :(
