### ISSUE TITLE
Using the plugin causes stickers to be grayed out

### ISSUE THREAD

**Issue by NarikoNep** [riolubruh/YABDP4Nitro#71]
I have everything related to Emojis and Stickers Disabled as I already have Nitro, I'm using the plugin for the Screenshare and other features, I'm unsure why this is happening and I was wondering if you could help resolve this issue.

![image](https://user-images.githubusercontent.com/97272732/219215540-f2762c17-7ebf-492b-b834-7ab12d2c1d85.png)
![Screenshot 2023-02-15 172819](https://user-images.githubusercontent.com/97272732/219216245-4e1352e8-3381-458b-86e4-9d90394e82da.png)

![image](https://user-images.githubusercontent.com/97272732/219215683-047a7fbf-7073-4b3e-acfa-1b06f4c975ab.png)

**Comment by riolubruh** [comment]
I don't really have a way to test things specifically for people with Nitro (because I don't actually have an account with nitro).
I have made some modifications to the plugin that I hope will help your issue. I have modified the way premiumType is modified (just in case), I have removed a piece of code that would lock the stickers (it was only intended to run if the person does not have Nitro), and just in case none of that works, I have also added an option to the settings that will force stickers to be unlocked if enabled.
This experimental version [can be found here.](https://github.com/riolubruh/YABDP4Nitro/files/10760502/YABDP4Nitro.plugin.zip) Please let me know if this is working as intended and I will then commit it to the repository.

**Comment by NarikoNep** [comment]
The first 2 solutions didn't work but the last one (The Force Unlock) does indeed work.

**Comment by NarikoNep** [comment]
And one more thing, anything pertaining to Nitro - Such as The User Profile, Server Profiles, and more that I may need to check do not work, it says that I do not have Nitro. If I edit something the Nitro advert disappears and I'm able to edit them, other than the Profile Gradient which is replaced with the normal banner color.
